"""next changes

Revision ID: 6ee9253edd9d
Revises: 312c6c13f9eb
Create Date: 2026-07-16 11:45:09.588348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6ee9253edd9d'
down_revision: Union[str, Sequence[str], None] = '312c6c13f9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_date', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
