"""update category model

Revision ID: 9edce04d6d83
Revises: e29bf2aa2b08
Create Date: 2026-07-11 15:33:47.641212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9edce04d6d83'
down_revision: Union[str, Sequence[str], None] = 'e29bf2aa2b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('category_name', sa.String(length=100), nullable=False))
    op.drop_column('category', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('category', 'category_name')
    # ### end Alembic commands ###
