"""date update in order model

Revision ID: cf10dfdf3821
Revises: 6ee9253edd9d
Create Date: 2026-07-16 11:45:56.305814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf10dfdf3821'
down_revision: Union[str, Sequence[str], None] = '6ee9253edd9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_date')
    # ### end Alembic commands ###
